import Command
import CoreML
import MLTensorUtils
import Testing
import TestingUtils

@testable import Embeddings

/*
 NOTE:
 The following test are testing the accuracy of the embeddings generated by the Swift models
 against the embeddings generated by the Python transformers library. They they are slow
 and require the [uv](https://github.com/astral-sh/uv) command line tool to be available.

 This suite can be run using the following command from the command line:

 ```
 PYTORCH_ENABLE_MPS_FALLBACK=1 UV_PATH=$(which uv) CI_DISABLE_NETWORK_MONITOR=1 swift test --filter AccuracyTests
 ```

*/

actor PythonRunner {
    static let shared = PythonRunner()

    func run(arguments: [String]) async throws -> String {
        try await Command
            .run(arguments: arguments)
            .pipedStream()
            .concatenatedString(including: [.standardOutput])
    }
}

func generateUsingTransformers(
    modelPath: String,
    texts: [String],
    modelType: ModelType
) async throws -> [Float] {
    let scriptUrl = try #require(
        Bundle.module.path(forResource: "generate", ofType: "py", inDirectory: "Scripts"),
        "Script not found"
    )
    let environment = ProcessInfo.processInfo.environment
    let arguments: [String]
    if let pythonPath = environment["PYTHON_PATH"] {
        arguments =
            [
                pythonPath, scriptUrl, "--model_dir", modelPath, "--type",
                modelType.rawValue,
            ] + texts.flatMap { ["--text", "\($0)"] }
    } else {
        let uvPath = try #require(environment["UV_PATH"], "UV_PATH not found")
        arguments =
            [
                uvPath, "run", "--quiet", scriptUrl, "--model_dir", modelPath, "--type",
                modelType.rawValue,
            ] + texts.flatMap { ["--text", "\($0)"] }
    }
    let result = try await PythonRunner.shared.run(arguments: arguments)
    return
        result
        .components(separatedBy: .newlines)
        .filter { !$0.isEmpty }
        .compactMap { Float($0) }
}

func modelPath(modelId: String, cacheDirectory: URL) -> String {
    cacheDirectory
        .appendingPathComponent("models")
        .appendingPathComponent(modelId)
        .path()
}

struct DownloadModelTrait: TestTrait, SuiteTrait, TestScoping {
    let modelId: String
    let downloadBase: URL

    func provideScope(
        for test: Test,
        testCase: Test.Case?,
        performing function: @Sendable () async throws -> Void
    ) async throws {
        try await downloadModelFromHub(
            from: modelId,
            downloadBase: downloadBase,
            useBackgroundSession: false
        )
        try await function()
    }
}

extension Trait where Self == DownloadModelTrait {
    static func downloadModel(modelId: String, downloadBase: URL) -> Self {
        Self(modelId: modelId, downloadBase: downloadBase)
    }
}

enum ModelType: String {
    case bert
    case clip
    case model2Vec = "model2vec"
    case modernbert = "modernbert"
    case nomic = "nomic"
    case roberta
    case staticEmbeddings = "static-embeddings"
    case xlmRoberta = "xlm-roberta"
}

enum Utils {
    static let modelPath: URL =
        if let modelPath = ProcessInfo.processInfo.environment["MODEL_PATH"] {
            URL(fileURLWithPath: modelPath)
        } else {
            FileManager.default.temporaryDirectory
        }

    static let batchTextsToTests: [String] = [
        "Hello!",
        "This is a long sentence so the other sentences are padded",
        "The dog barks",
    ]
}

extension Utils {
    enum ModelId {
        static let bert = "google-bert/bert-base-uncased"
        static let clip = "jkrukowski/clip-vit-base-patch32"
        static let model2Vec = "minishlab/potion-base-2M"
        static let modernBertBase = "answerdotai/ModernBERT-base"
        static let modernBertNomic = "nomic-ai/modernbert-embed-base"
        static let nomicEmbedTextV15 = "nomic-ai/nomic-embed-text-v1.5"
        static let roberta = "FacebookAI/roberta-base"
        static let staticEmbeddings = "sentence-transformers/static-retrieval-mrl-en-v1"
        static let xlmRoberta = "FacebookAI/xlm-roberta-base"
    }
}
